version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gomess-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gomess
      MYSQL_USER: gomess
      MYSQL_PASSWORD: 123456

    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: gomess-redis

    ports:
      - "6379:6379"
